# Generated by Django 3.1.6 on 2021-02-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCIVUser',
        ),
    ]
